-* 
   Copyright 2025, ...

   You may redistribute this file under the terms of the GNU General Public
   License as published by the Free Software Foundation, either version 2 of
   the License, or any later version.
*-

-- This module computes orbit sums of special monomials under the action of a permutation group.
-- It includes functions to generate and check special monomials and to compute orbit sums.
-- Designed for use inside the InvariantRing package.

-------------------------------------------
--- PermutationAction: actions by variable permutations
-------------------------------------------

-- dependencies
needsPackage "SRdeformations"
needsPackage "Permutations"

-------------------------------------------
--- Declare symbols used as dictionary keys
-------------------------------------------
symbol ring
symbol generators
symbol numgens
symbol permMatrices   -- optional: adds clarity if you ever access it later

-------------------------------------------

PermutationAction = new Type of GroupAction    -- the PermutationAction object
permutationAction = method()                   -- constructor dispatcher

-------------------------------------------
--- PermutationAction constructor
--- permutationAction : (List of Permutation, PolynomialRing) -> PermutationAction
-------------------------------------------

permutationAction (List, PolynomialRing) := PermutationAction => (W, R) -> (
    if not isField coefficientRing R then (
        error "permutationAction: expected the second argument to be a polynomial ring over a field."
    );
    if any(W, w -> not instance(w, Permutation)) then (
        error "permutationAction: expected a list of objects of class Permutation."
    );
    n := dim R;
    maps := apply(W, w -> Core$matrix(w, Degree => n));
    -- NOTE: use STRING key "permMatrices" to avoid package-level symbol creation
    new PermutationAction from {
        cache => new CacheTable,
        (symbol ring) => R,
        (symbol generators) => W,
        (symbol numgens) => #W,
        "permMatrices" => maps
    }
)

net PermutationAction := A -> (net A.ring) | " <- Permutations(" | toString(A.numgens) | ")"
generators PermutationAction := A -> A.generators
numgens    PermutationAction := ZZ => A -> A.numgens

-------------------------------------------
-- helpers: special monomials & orbit sums
-------------------------------------------

-- Return all weakly-decreasing n-tuples of nonnegative integers summing to d.
specialExponents = method()
specialExponents (ZZ, ZZ) := List => (n, d) -> (
    if d < 0 then return {};
    if n == 0 then return (if d == 0 then {{} } else {});
    local acc; 
    local rec; 
    acc = {};
    -- use scan(reverse(...)) to avoid by -1 and avoid leaking function names
    rec = (k, rem, lastmax, prefix) -> (
        if k == n then (
            if rem <= lastmax then (acc = append(acc, prefix | {rem}))
        ) else (
            scan(reverse(0 .. min(rem, lastmax)), a -> (
                rec(k+1, rem - a, a, prefix | {a})
            ))
        )
    );
    rec(1, d, d, {}); 
    acc 
)

-- convert exponent vector to monomial of ring R
monomialFromExp = method()
monomialFromExp (PolynomialRing, List) := RingElement => (R, v) -> (
    g := gens R;
    n := #v;
    product apply(n, i -> g_i^(v#i))
)

-- extract mapping list [w(1),...,w(n)] from a Permutation’s matrix
permMap = method()
permMap (Permutation, ZZ) := List => (w, n) -> (
    P := Core$matrix(w, Degree => n);
    apply(n, i -> (
        jj := first select(toList(0..n-1), j -> P_(i,j) == 1);
        jj + 1
    ))
)

-- apply a permutation map to an exponent vector:
-- result at position w(i) gets v_i  (i.e. v'_{w(i)} = v_i)
applyPermToExp = method()
applyPermToExp (List, List) := List => (v, wmap) -> (
    n := #v;
    res := for i to n-1 list 0;
    for i to n-1 do res_(wmap#i - 1) = v#i;
    res
)

-- BFS orbit under the subgroup generated by W on exponent vectors
orbitOfVector = method()
orbitOfVector (List, List, ZZ) := List => (v, W, n) -> (
    wmaps := apply(W, w -> permMap(w, n));
    seen := new MutableHashTable;
    keyOf := u -> toString u;
    Q := {v};
    seen#(keyOf v) = true;
    idx := 0;
    while idx < #Q do (
        u := Q#idx;
        for wmap in wmaps do (
            u2 := applyPermToExp(u, wmap);
            k := keyOf u2;
            if not seen#?k then (
                seen#k = true;
                Q = append(Q, u2);
            )
        );
        idx = idx + 1;
    );
    Q
)

-- orbit sum of a monomial with exponent vector v
orbitSumFromExp = method()
orbitSumFromExp (PermutationAction, List) := RingElement => (A, v) -> (
    R := ring A;
    n := dim R;
    W := generators A;
    orb := orbitOfVector(v, W, n);
    sum orb / (u -> monomialFromExp(R, u))
)

-- list of special monomials in degree d (as actual monomials)
specialMonomials = method()
specialMonomials (PermutationAction, ZZ) := List => (A, d) -> (
    R := ring A;
    n := dim R;
    exps := specialExponents(n, d);
    apply(exps, v -> monomialFromExp(R, v))
)

-------------------------------------------
-- row/column permutation helpers (operator-free public API)
-------------------------------------------

permuteRows = method()
permuteRows (Permutation, Matrix) := (p, M) -> (
    n := numRows M;
    P := Core$matrix(p, Degree => n);
    P * M
)

permuteColumns = method()
permuteColumns (Matrix, Permutation) := (M, p) -> (
    n := numColumns M;
    P := Core$matrix(p, Degree => n);
    M * P
)

-------------------------------------------
-- permutationAction convenience
-------------------------------------------

permutationAction (Permutation, Thing) := Thing => (p, x) -> (
    if instance(x, Matrix) then permuteColumns(x, p)
    else if instance(x, List) then (
        n := #x;
        wmap := permMap(p, n);
        apply(n, i -> x_(wmap#i - 1))
    )
    else error "permutationAction: unsupported object type"
)

-------------------------------------------
-- invariants by orbit sums (compatible with InvariantRing style)
-------------------------------------------

invariants (PermutationAction, ZZ) := List => opts -> (A, d) -> (
    if d < 0 then return {};
    if d == 0 then return {1_(ring A)};
    R := ring A;
    if zero basis(d, R) then return {};
    mons := specialMonomials(A, d);
    L := apply(mons, f -> (
        v := (exponents f)_0;
        orbitSumFromExp(A, v)
    ));
    toList set L
)

invariants PermutationAction := List => opts -> A -> (
    R := ring A;
    if unique degrees R =!= {{1}} then error "Only implemented for standard graded polynomial rings";
    b := opts.DegreeBound;
    if b === infinity then b = product(1 .. dim R);  -- factorial replacement without introducing a new symbol
    S := {};
    local M;
    for d from 1 to b+1 do (
        Gb := gb(promote(ideal S, R), DegreeLimit => d);
        I := monomialIdeal leadTerm Gb;
        M = reverse select(flatten entries (basis(d, R) % I), m -> not zero m);
        if d == b+1 then break;
        if #M > 0 then (
            Id := invariants(A, d);
            S  = join(S, Id);
        )
    );
    manualTrim S
)
